@startuml
left to right direction
package system{
    usecase "function1" as f1
    usecase "function2" as f2
}
:user:-->f1
:user:-->f2
package system2{
    usecase "function1" as f3
    usecase "function2" as f4
}
:user:-->f3
:user:-->f4
@enduml